# Generated by Django 5.1.7 on 2025-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userbodyrecord_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "User"},
        ),
        migrations.AlterModelOptions(
            name="userbodyrecord",
            options={
                "ordering": ["-date"],
                "verbose_name": "Body Metrics Record",
                "verbose_name_plural": "Body Metrics Record",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="Height(cm)"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, upload_to="profile_pics", verbose_name="Profile Picture"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="target_weight",
            field=models.FloatField(
                blank=True, null=True, verbose_name="target_weight(kg)"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.FloatField(blank=True, null=True, verbose_name="Weight(kg)"),
        ),
        migrations.AlterField(
            model_name="userbodyrecord",
            name="body_fat",
            field=models.FloatField(blank=True, null=True, verbose_name="Body Fat(%)"),
        ),
        migrations.AlterField(
            model_name="userbodyrecord",
            name="chest",
            field=models.FloatField(blank=True, null=True, verbose_name="Chest(cm)"),
        ),
        migrations.AlterField(
            model_name="userbodyrecord",
            name="date",
            field=models.DateField(verbose_name="Record Date"),
        ),
        migrations.AlterField(
            model_name="userbodyrecord",
            name="hips",
            field=models.FloatField(blank=True, null=True, verbose_name="Hips(cm)"),
        ),
        migrations.AlterField(
            model_name="userbodyrecord",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="userbodyrecord",
            name="waist",
            field=models.FloatField(blank=True, null=True, verbose_name="Waist(cm)"),
        ),
        migrations.AlterField(
            model_name="userbodyrecord",
            name="weight",
            field=models.FloatField(verbose_name="Weight(kg)"),
        ),
    ]
