# Generated by Django 5.1.7 on 2025-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={"verbose_name": "Exercise", "verbose_name_plural": "Exercise"},
        ),
        migrations.AlterModelOptions(
            name="workout",
            options={
                "ordering": ["-date", "-start_time"],
                "verbose_name": "Workout Record",
                "verbose_name_plural": "Workout Record",
            },
        ),
        migrations.AlterModelOptions(
            name="workoutcategory",
            options={
                "verbose_name": "Fitness category",
                "verbose_name_plural": "Fitness category",
            },
        ),
        migrations.AlterModelOptions(
            name="workoutexercise",
            options={
                "verbose_name": "Exercise Record",
                "verbose_name_plural": "Exercise Record",
            },
        ),
        migrations.AlterModelOptions(
            name="workoutplan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "WorkoutPlan",
                "verbose_name_plural": "WorkoutPlan",
            },
        ),
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Exercise Name"),
        ),
        migrations.AlterField(
            model_name="workout",
            name="calories_burned",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Calories Burned"
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="workout",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="Duration"),
        ),
        migrations.AlterField(
            model_name="workout",
            name="end_time",
            field=models.TimeField(verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="workout",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="workout",
            name="start_time",
            field=models.TimeField(verbose_name="Start Time"),
        ),
        migrations.AlterField(
            model_name="workoutcategory",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="workoutcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Category name"),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="reps",
            field=models.CharField(max_length=50, verbose_name="Reps Per Set"),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="sets",
            field=models.IntegerField(verbose_name="Sets"),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="weight",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Weight(kg)"
            ),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="description",
            field=models.TextField(blank=True, verbose_name="Plan Description"),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Plan Title"),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
